<?php
include(dirname(__FILE__).'/phpMyEditHeader.php');

//if (!defined('DEBUG')) define('DEBUG', 1);

function phpMyEditPageHeader($inst) {
    if (in_array($inst->{'page_type'}, array('L', 'A', 'C', 'V', 'D'))) {
        $commande = $inst->{'fdd'}['commande_id']['default'];
        $row = $inst->QueryDB("SELECT * FROM `commandes` WHERE `rowid` = $commande");
        if (defined('DEBUG')) echo print_r($row, true) . "\n";
        if ($row['co_type'] == 'Fabrication') {
            echo "<pre>
Batch   : {$row['co_type']} #{$commande} - {$row['date_commande']} - {$row['commentaires']}
Usine   : {$row['pa_code']}
</pre>";
        } else {
            echo "<pre>
Commande: {$row['co_type']} #{$commande} - {$row['date_commande']} - {$row['commentaires']}
Client  : {$row['pa_code']}
Payé le : {$row['date_paiement']}
</pre>";            
        }
    }
/*
    if (defined('DEBUG')) {
        echo '<pre>' . "\n";
        echo 'Inside obj: ' . print_r($inst, true);
        echo '</pre>' . "\n";            
    }
*/
}

function phpMyEditPageFooter($inst) {
    if (in_array($inst->{'page_type'}, array('L'))) {
        $commande = $inst->{'fdd'}['commande_id']['default'];
        $row = $inst->QueryDB("SELECT * FROM `commandes` WHERE `rowid` = $commande");
        if (defined('DEBUG')) echo print_r($row, true) . "\n";  
        if ($row['co_type'] == 'Fabrication') {
            echo "<pre>
{$row['articles']} Article(s)
</pre>";        
        } else {
            echo "<pre>
{$row['articles']} Article(s) pour un total de {$row['prixtotal']} USD
</pre>";        
        }
    }
}

?>

<?php

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, please check the documentation. It is available
 * on the phpMyEdit pages or in the manuals folder. Some information can also be
 * found in the lib/configoptions.md file.
 *
 * https://sourceforge.net/projects/phpmariaedit/
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.6
 *        lib/phpMyEdit.class.php class: 5.7.6
 *            phpMyEditSetup.php script: 5.7.6
 *                     generated script: 5.7.6
 *
 * This file was manually updated.
 */

require_once(dirname(__FILE__).'/lib/extensions/phpMyEdit-multiquery.class.php');
require_once(dirname(__FILE__).'/lib/phpMyEditDB.php');
require_once(dirname(__FILE__).'/phpMyEditDefaults.php');

$opts['tb'] = 'comdetails';

// custom settings overwriting general edit defaults
$opts['cgi']['prefix']['data'] = 'comdetails_';
$opts['cgi']['persist'] = array('commande_id' => $_REQUEST['commande_id'],
                                'oper' => $_REQUEST['oper']);

$orderID = $opts['cgi']['persist']['commande_id'];
$oper = $opts['cgi']['persist']['oper'];
if ($oper == 'Fabrication') $oper = 'Vente';

if ($opts['cgi']['persist']['oper'] == 'List') $opts['options'] = 'VL';
else $opts['options'] = 'ACVDL';

$opts['display']['sort'] = false;

// filter on subset
$opts['filters'] = "`commande_id`=" . $orderID;

// Name of field which is the unique key
$opts['key'] = 'rowid';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';
// Sorting field(s)
$opts['sort_field'] = array('rowid');

/* please refer to lib/phpMyEditInfo.php for additional options
   that can be added in this file
*/

$opts['fdd']['rowid'] = array(
         'name' => 'ID',
       'select' => 'T',
      'options' => 'VDR', // auto increment
       'maxlen' => '10',
           'js' => array('required' => true),
      'default' => '0',
         'sort' => true
);
$opts['fdd']['commande_id'] = array(
         'name' => 'Commande ID',
       'select' => 'T',
      'options' => 'ACPVDH',
       'maxlen' => '10',
      'default' => $orderID,
       'values' => array('table'  => 'commandes',
                         'column' => 'rowid',
                         'description' => array('columns' => array('date_commande', 'pa_code'),
                                                'divs'    => array (' - ')),
                         'filters' => 'rowid = ' .  $orderID 
                        ),
         'sort' => true
);
$opts['fdd']['pr_code'] = array(
         'name' => 'Produit',
       'select' => 'T',
       'maxlen' => '8',
           'js' => array('required' => true),
       'values' => array('table'  => 'products',
                         'column' => 'pr_code',
                         'description' => array('columns' => array('pr_code', 'pr_name', 'pr_unite'),
                                                'divs'    => array (' - ', ' (', ')'))
                        ),
         'sort' => true
);
if (isset($oper) && ($oper != '')) {
    $opts['fdd']['pr_code']['values']['filters'] = 'pr_type = "' . $oper . '"'; 
}
$opts['fdd']['quantite'] = array(
         'name' => 'Quantite',
       'select' => 'N',
       'maxlen' => '10',
      'default' => '1.00'
);
$opts['fdd']['commentaires'] = array(
         'name' => 'Commentaires',
       'select' => 'T',
     'textarea' => array('rows' => 5, 'cols' => 80)
);

echo '
<script>
    PME_js_setPageTitle("");
</script>
';

// Now important call to phpMyEdit

new phpMyEdit_MultiQuery($opts);

//eof

