<?php
include(dirname(__FILE__).'/phpMyEditHeader.php');
?>

<?php

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, please check the documentation. It is available
 * on the phpMyEdit pages or in the manuals folder. Some information can also be
 * found in the lib/configoptions.md file.
 *
 * https://sourceforge.net/projects/phpmariaedit/
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.6
 *        lib/phpMyEdit.class.php class: 5.7.6
 *            phpMyEditSetup.php script: 5.7.6
 *                     generated script: 5.7.6
 *
 * This file was NOT manually updated.
 */

require_once(dirname(__FILE__).'/lib/phpMyEdit.class.php');
require_once(dirname(__FILE__).'/lib/phpMyEditDB.php');
require_once(dirname(__FILE__).'/phpMyEditDefaults.php');

$opts['tb'] = 'ingredients';

// Name of field which is the unique key
$opts['key'] = 'in_code';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'char';
// Sorting field(s)
$opts['sort_field'] = array('in_code');

/* please refer to lib/phpMyEditInfo.php for additional options
   that can be added in this file
*/

$opts['fdd']['in_code'] = array(
         'name' => 'Code',
       'select' => 'T',
       'maxlen' => '8',
           'js' => array('required' => true),
         'sort' => true
);
$opts['fdd']['in_name'] = array(
         'name' => 'Name',
       'select' => 'T',
       'maxlen' => '60',
           'js' => array('required' => true),
         'sort' => true
);
$opts['fdd']['in_unite'] = array(
         'name' => 'Unité',
       'select' => 'M',
       'maxlen' => '2',
       'values' => array(
                  "KG",
                  "L",
                  ""),
           'js' => array('required' => true),
         'sort' => true
);
$opts['fdd']['status_code'] = array(
         'name' => 'Status code',
       'select' => 'T',
       'maxlen' => '1',
      'default' => 'C',
       'values' => array('table'  => 'pme_statuscodes',
                         'column' => 'code',
                         'description' => array('columns' => array('code', 'status_name'),
                                                'divs'    => array (' - '))
                        ),
         'sort' => true
);

// possibly initialise page further before going to main function

if (function_exists('phpMyEditHeaderInit')) { phpMyEditHeaderInit($opts); }

// now copy php variables over to js variables
// protect sensitive variables so they cannot be read
$cleanopts = $opts;
unset($cleanopts['hn']); unset($cleanopts['pt']);
unset($cleanopts['un']); unset($cleanopts['pw']);

echo '
<script>
    var phpOpts = ' . json_encode($cleanopts) . ';
    try {
        if (typeof PME_js_init === \'function\') {
            PME_js_init(phpOpts);
        }
    } catch(err) {
        console.log(err);
    }
</script>
';

// Now important call to phpMyEdit

new phpMyEdit($opts);

//eof

