<menu class='pme-menu'>
    <li></li>
    <li><a href='ingredients.php?menu=admin'>Ingredients</a></li>
    <li><a href='products.php?menu=admin&oper=Achat'>Produits</a></li>
    <li><a href='products.php?menu=admin&oper=Vente'>Produits de vente</a></li>
    <li><a href='partners.php?menu=admin'>Partenaires</a></li>
    <li><a href='commandes.php?menu=admin&oper=Fabrication&status'>Fabrication</a></li>
    <li><a href='commandes.php?menu=admin&oper=List&status=Open'>Liste-commandes</a></li>
    <li><a href='reports.php?menu=admin'>Rapports</a></li>
    <li class='not-vertical'><a href='animaux.php?menu=admin'>Animaux</a></li>
</menu>