<menu class='pme-menu'>
    <li></li>
    <li><a href='fournisseurs.php?menu=user'>Fournisseurs</a></li>
    <li><a href='commandes.php?menu=user&oper=Achat&status=Open'>Achats</a></li>
    <li><a href='commandes.php?menu=user&oper=List&status=Closed'>Anciennes-commandes</a></li>
    <li><a href='commandes.php?menu=user&oper=Achat&status=Closed'>Anciens-Achats</a></li>
    <li><a href='commandes.php?menu=user&oper=Vente&status=Closed'>Anciennes-Ventes</a></li>
    <li><a href='operations.php?menu=user&oper=Achat'>Livraison-paiement (IN)</a></li>
</menu>