<menu class='pme-menu'>
    <li><a href='index.php'><img class="pme-navigation" src="images/pme-home.png" alt="Home"></a></li>
    <li><a href='products.php'>Produits</a></li>
    <li><a href='animaux.php'>Animaux</a></li>
    <li><a href='achats.php'>Achats</a></li>
    <li><a href='ventes.php'>Ventes</a></li>
    <li><a href='examples/symbols.php'>Symbols</a></li>
    <li><a href='examples/languages.php'>Languages</a></li>
    <li><a href='examples/statuscodes.php'>StatusCodes</a></li>
    <li><a href='examples/users.php'>Users</a></li>
</menu>