<menu class='pme-menu'>
    <li><a href='/'><img class="pme-navigation" src="images/pme-home.png" alt="Home"></a></li>
    <li><a href='ingredients.php'>Ingredients</a></li>
    <li><a href='products.php'>Produits</a></li>
    <li><a href='partners.php'>Partenaires</a></li>
    <li><a href='clients.php'>Clients</a></li>
    <li><a href='fournisseurs.php'>Fournisseurs</a></li>
    <li><a href='commandes.php?oper=Fabrication&status'>Fabrication</a></li>
    <li><a href='commandes.php?oper=List&status=Open'>Liste-commandes</a></li>
    <li><a href='commandes.php?oper=List&status=Closed'>Anciennes-commandes</a></li>
    <li><a href='commandes.php?oper=Achat&status=Open'>Commandes-Achats</a></li>
    <li><a href='commandes.php?oper=Vente&status=Open'>Commandes-Ventes</a></li>
    <li><a href='commandes.php?oper=Achat&status=Closed'>Anciens-Achats</a></li>
    <li><a href='commandes.php?oper=Vente&status=Closed'>Anciens-Ventes</a></li>
    <li><a href='operations.php?oper=Livraison'>Livraisons (IN)</a></li>
    <li><a href='operations.php?oper=Vente'>Paiement client</a></li>
    <li class='not-vertical'><a href='animaux.php'>Animaux</a></li>
</menu>