<menu class='pme-menu'>
    <li><a href='/'><img class="pme-navigation" src="images/pme-home.png" alt="Home"></a></li>
    <li><a href='fournisseurs.php'>Fournisseurs</a></li>
    <li><a href='commandes.php?oper=Achat&status=Open'>Achats</a></li>
    <li><a href='commandes.php?oper=List&status=Closed'>Anciennes-commandes</a></li>
    <li><a href='commandes.php?oper=Achat&status=Closed'>Anciens-Achats</a></li>
    <li><a href='commandes.php?oper=Vente&status=Closed'>Anciennes-Ventes</a></li>
    <li><a href='operations.php?oper=Livraison'>Livraisons (IN)</a></li>
</menu>