<menu class='pme-menu'>
    <li><a href='/'><img class="pme-navigation" src="images/pme-home.png" alt="Home"></a></li>
    <li><a href='ingredients.php'>Ingredients</a></li>
    <li><a href='products.php?oper=Achat'>Produits</a></li>
    <li><a href='products.php?oper=Vente'>Produits de vente</a></li>
    <li><a href='partners.php'>Partenaires</a></li>
    <li><a href='commandes.php?oper=Fabrication&status'>Fabrication</a></li>
    <li><a href='commandes.php?oper=List&status=Open'>Liste-commandes</a></li>
    <li><a href='reports.php'>Rapports</a></li>
    <li class='not-vertical'><a href='animaux.php'>Animaux</a></li>
</menu>