<?php
include(dirname(__FILE__).'/phpMyEditHeader.php');
?>

<?php

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, please check the documentation. It is available
 * on the phpMyEdit pages or in the manuals folder. Some information can also be
 * found in the lib/configoptions.md file.
 *
 * https://sourceforge.net/projects/phpmariaedit/
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.6
 *        lib/phpMyEdit.class.php class: 5.7.6
 *            phpMyEditSetup.php script: 5.7.6
 *                     generated script: 5.7.6
 *
 * This file was manually updated.
 */

require_once(dirname(__FILE__).'/lib/phpMyEdit.class.php');
require_once(dirname(__FILE__).'/lib/phpMyEditDB.php');
require_once(dirname(__FILE__).'/phpMyEditDefaults.php');

$opts['tb'] = 'partners';

// custom settings overwriting general edit defaults
$opts['display']['sort'] = false;

// Name of field which is the unique key
$opts['key'] = 'pa_code';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'char';
// Sorting field(s)
$opts['sort_field'] = array('pa_code');

$opts['options'] = 'ACVDF';

/* please refer to lib/phpMyEditInfo.php for additional options
   that can be added in this file
*/

$opts['fdd']['pa_code'] = array(
         'name' => 'Code',
       'select' => 'T',
         'help' => 'The partner code, cannot be changed once used',
       'maxlen' => '8',
           'js' => array('required' => true),
         'sort' => true
);
$opts['fdd']['pa_name'] = array(
         'name' => 'Name',
       'select' => 'T',
         'help' => 'The partner name',
       'maxlen' => '60',
           'js' => array('required' => true),
         'sort' => true
);
$opts['fdd']['pa_phone'] = array(
         'name' => 'Phone',
       'select' => 'T',
         'help' => 'The partner phone',
       'maxlen' => '60'
);
$opts['fdd']['pa_mail'] = array(
         'name' => 'e-mail',
       'select' => 'T',
         'help' => 'The partner mail',
       'maxlen' => '60'
);
$opts['fdd']['pa_type'] = array(
         'name' => 'Type',
       'select' => 'C',
       'maxlen' => '11',
       'values' => array(
                  "Fournisseur",
                  "Client",
                  "Usine")
);
$opts['fdd']['commentaires'] = array(
         'name' => 'Commentaires',
       'select' => 'T',
     'textarea' => array('rows' => 5, 'cols' => 80)
);
$opts['fdd']['status_code'] = array(
         'name' => 'Status code',
       'select' => 'T',
      'options' => 'VCPDR',
         'help' => 'valid codes: see table pme_statuscodes',
       'maxlen' => '1',
      'default' => 'C',
       'values' => array('table'  => 'pme_statuscodes',
                         'column' => 'code',
                         'description' => array('columns' => array('code', 'status_name'),
                                                'divs'    => array (' - '))
                        )
);

// possibly initialise page further before going to main function

if (function_exists('phpMyEditHeaderInit')) { phpMyEditHeaderInit($opts); }

echo '
<script>
    PME_js_setPageTitle("Partenaires");
</script>
';

// Now important call to phpMyEdit

new phpMyEdit($opts);

//eof

