<?php
include(dirname(__FILE__).'/phpMyEditHeader.php');
include_once(dirname(__FILE__).'/functions.inc');

function phpMyEditPageHeader($inst) {

    $productID = $inst->{'fdd'}['pr_code']['default'];
    $sql = "SELECT * FROM `products` WHERE `pr_code` = '" . $productID . "'";
    $product = $inst->QueryDB($sql);
    $productName = $product['pr_name'];

    echo "<h3><a href='products.php?oper=Vente&PME_sys_fl=0&PME_sys_fm=0&PME_sys_sfn[0]=0&PME_sys_operation=PME_op_View&PME_sys_rec=$productID'>Produit $productID - $productName</a></h3>\n";
}

function phpMyEditPageFooter($inst) {
    if (in_array($inst->{'page_type'}, array('L'))) {
        $productID = $inst->{'fdd'}['pr_code']['default'];
        $sql = "SELECT `pr_name` AS 'Produit', concat(`pr_prixunite`, '$ pour ', `pr_quantite`, ' ', `sy_value`) AS 'Prix de vente' FROM `products`, `pme_symbols` WHERE `sy_name` = 'UNITS' AND `sy_code` = `pr_unite` AND `pr_code` = '" . $productID . "'";
        $product = $inst->QueryDB($sql);
        PrintAssociateLine($product);
    }
}

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, please check the documentation. It is available
 * on the phpMyEdit pages or in the manuals folder. Some information can also be
 * found in the lib/configoptions.md file.
 *
 * https://sourceforge.net/projects/phpmariaedit/
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.6
 *        lib/phpMyEdit.class.php class: 5.7.6
 *            phpMyEditSetup.php script: 5.7.6
 *                     generated script: 5.7.6
 *
 * This file was manually updated.
 */

require_once(dirname(__FILE__).'/lib/extensions/phpMyEdit-multiquery.class.php');
require_once(dirname(__FILE__).'/lib/phpMyEditDB.php');
require_once(dirname(__FILE__).'/phpMyEditDefaults.php');

// custom settings overwriting general edit defaults
$opts['cgi']['prefix']['data'] = 'prodcomp_';
$opts['cgi']['persist'] = array('pr_code' => $_REQUEST['pr_code']);

$productID = $opts['cgi']['persist']['pr_code'];
$opts['filters'] = "`PMEtable0`.`pr_code` = '" . $productID . "'";

$opts['options'] = 'ACVDL';
$opts['navigation'] = 'GD';
$opts['display']['sort'] = false;

$opts['tb'] = 'prodcomposition';

// Name of field which is the unique key
$opts['key'] = 'rowid';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';

// Sorting field(s)
$opts['sort_field'] = array('rowid');

/* please refer to lib/phpMyEditInfo.php for additional options
   that can be added in this file
*/

$opts['fdd']['rowid'] = array(
         'name' => 'ID',
       'select' => 'T',
      'options' => 'VDR', // auto increment
       'maxlen' => '10',
           'js' => array('required' => true),
      'default' => '0'
);
$opts['fdd']['pr_code'] = array(
         'name' => 'Product',
       'select' => 'T',
      'options' => 'ACPDR',
       'maxlen' => '8',
           'js' => array('required' => true),
       'values' => array('table'  => 'products',
                         'column' => 'pr_code',
                         'description' => array('columns' => array('pr_code', 'pr_name', 'pr_unite'),
                                                'divs'    => array (' - ', ' (', ')')),
                         'filters' => "`products`.`pr_code` = '" . $productID . "'"
                        ),
      'default' => $productID
);
$opts['fdd']['in_code'] = array(
         'name' => 'Ingredient',
       'select' => 'T',
       'maxlen' => '8',
           'js' => array('required' => true),
       'values' => array('table'  => 'ingredients',
                         'column' => 'in_code',
                         'description' => array('columns' => array('in_code', 'in_name', 'in_unite'),
                                                'divs'    => array (' - ', ' (', ')'))
                        )
);
$opts['fdd']['quantite'] = array(
         'name' => 'Quantite',
       'select' => 'N',
       'maxlen' => '10',
      'default' => '1.00'
);

echo '
<script>
    PME_js_setPageTitle("Composition produit");
</script>
';

// Now important call to phpMyEdit

new phpMyEdit_MultiQuery($opts);

//eof
