<?php
include(dirname(__FILE__).'/phpMyEditHeader.php');
?>

<?php

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, please check the documentation. It is available
 * on the phpMyEdit pages or in the manuals folder. Some information can also be
 * found in the lib/configoptions.md file.
 *
 * https://sourceforge.net/projects/phpmariaedit/
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.6
 *        lib/phpMyEdit.class.php class: 5.7.6
 *            phpMyEditSetup.php script: 5.7.6
 *                     generated script: 5.7.6
 *
 * This file was manually updated.
 */

require_once(dirname(__FILE__).'/lib/phpMyEdit.class.php');
require_once(dirname(__FILE__).'/lib/phpMyEditDB.php');
require_once(dirname(__FILE__).'/phpMyEditDefaults.php');

$opts['options'] = 'ACVDL';
$opts['navigation'] = 'BD';
$opts['display']['sort'] = false;

$opts['tb'] = 'prodcomposition';

// Name of field which is the unique key
$opts['key'] = 'rowid';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';
// Sorting field(s)
$opts['sort_field'] = array('rowid');

/* please refer to lib/phpMyEditInfo.php for additional options
   that can be added in this file
*/

$opts['fdd']['rowid'] = array(
         'name' => 'ID',
       'select' => 'T',
      'options' => 'VDR', // auto increment
       'maxlen' => '10',
           'js' => array('required' => true),
      'default' => '0'
);
$opts['fdd']['pr_code'] = array(
         'name' => 'Product',
       'select' => 'T',
       'maxlen' => '8',
           'js' => array('required' => true),
       'values' => array('table'  => 'products',
                         'column' => 'pr_code',
                         'description' => array('columns' => array('pr_code', 'pr_name'),
                                                'divs'    => array (' - '))
                        ),
         'sort' => true
);
$opts['fdd']['in_code'] = array(
         'name' => 'Ingredient',
       'select' => 'T',
       'maxlen' => '8',
           'js' => array('required' => true),
       'values' => array('table'  => 'ingredients',
                         'column' => 'in_code',
                         'description' => array('columns' => array('in_code', 'in_name'),
                                                'divs'    => array (' - '))
                        )
);
$opts['fdd']['quantite'] = array(
         'name' => 'Quantite',
       'select' => 'N',
       'maxlen' => '10',
      'default' => '1.00'
);

// possibly initialise page further before going to main function

if (function_exists('phpMyEditHeaderInit')) { phpMyEditHeaderInit($opts); }

// now copy php variables over to js variables
// protect sensitive variables so they cannot be read
$cleanopts = $opts;
unset($cleanopts['hn']); unset($cleanopts['pt']);
unset($cleanopts['un']); unset($cleanopts['pw']);

echo '
<script>
    var phpOpts = ' . json_encode($cleanopts) . ';
    try {
        if (typeof PME_js_init === \'function\') {
            PME_js_init(phpOpts);
        }
    } catch(err) {
        console.log(err);
    }
    PME_js_setPageTitle("Composition de produit");
</script>
';

// Now important call to phpMyEdit

new phpMyEdit($opts);

//eof

