<?php
include(dirname(__FILE__).'/phpMyEditHeader.php');
include_once(dirname(__FILE__).'/functions.inc');

function phpMyEditPageFooter($inst) {
    if (in_array($inst->{'page_type'}, array('A', 'C', 'V', 'D'))
        && ($inst->{'fdd'}['pr_type']['default'] == 'Vente')) {
        $sql = "SELECT `in_name` AS 'Ingredient',
                        concat(`quantite`, ' ', `in_unite`) AS 'Quantité',
                        FORMAT(quantite * in_prixunite,2) AS 'Coût'
        FROM `prodcomposition`, `ingredients`
        WHERE `pr_code` = '" . $inst->{'rec'} . "'
          AND `prodcomposition`.`in_code` = `ingredients`.`in_code`
        UNION
        SELECT '<strong>Total</strong>' AS 'Ingredient',
               '' AS 'Quantité',
               FORMAT(SUM(quantite * in_prixunite),2) AS 'Coût'
        FROM `prodcomposition`, `ingredients`
        WHERE `pr_code` = '" . $inst->{'rec'} . "'
          AND `prodcomposition`.`in_code` = `ingredients`.`in_code`";
        PrintAssociateTable($inst, $sql);
    }
}

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, please check the documentation. It is available
 * on the phpMyEdit pages or in the manuals folder. Some information can also be
 * found in the examples/configoptions.md file.
 *
 * https://sourceforge.net/projects/phpmariaedit/
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.6
 *        lib/phpMyEdit.class.php class: 5.7.6
 *            phpMyEditSetup.php script: 5.7.6
 *                     generated script: 5.7.6
 *
 * This file was manually updated.
 */

require_once(dirname(__FILE__).'/lib/extensions/phpMyEdit-multiquery.class.php');
require_once(dirname(__FILE__).'/lib/phpMyEditDB.php');
require_once(dirname(__FILE__).'/phpMyEditDefaults.php');

$opts['cgi']['persist'] = array('oper' => $_REQUEST['oper']);
if ($opts['cgi']['persist']['oper'] == 'Vente') {
    $title = "Produits pour la vente";
    $titleLink = 'products.php?oper=Vente';
} else {
    $title = "Produits achat stock";
    $titleLink = 'products.php?oper=Achat';
}
$opts['filters'] = "`pr_type` = '" . $opts['cgi']['persist']['oper'] . "'";

// custom settings
$opts['options'] = 'ACVD';
$opts['display']['sort'] = false;

$opts['tb'] = 'products';

// Name of field which is the unique key
$opts['key'] = 'pr_code';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'char';

// Sorting field(s)
$opts['sort_field'] = array('pr_code');

$opts['fdd']['pr_code'] = array(
         'name' => 'Code',
       'select' => 'T',
       'maxlen' => '8',
           'js' => array('required' => true),
         'sort' => true
);
$opts['fdd']['pr_name'] = array(
         'name' => 'Name',
       'select' => 'T',
       'maxlen' => '60',
           'js' => array('required' => true),
         'sort' => true
);
$opts['fdd']['pr_type'] = array(
         'name' => 'Type',
       'select' => 'C',
      'options' => 'VDR',
       'maxlen' => '5',
       'values' => array(
                  "Achat",
                  "Vente"),
           'js' => array('required' => true),
      'default' => $opts['cgi']['persist']['oper']
);
$opts['fdd']['pr_unite'] = array(
         'name' => 'Unité',
       'select' => 'T',
       'maxlen' => '10',
      'default' => 'Pce',
           'js' => array('required' => true),
       'values' => array('table'  => 'pme_symbols',
                         'column' => 'sy_code',
                         'description' => array('columns' => array('sy_value')),
                         'filters' => 'sy_name = "UNITS"'
                        )
);
$opts['fdd']['pr_quantite'] = array(
         'name' => 'Quantité',
       'select' => 'N',
       'maxlen' => '10',
      'default' => '1.00'
);
$opts['fdd']['pr_prixunite'] = array(
       'select' => 'N',
       'maxlen' => '10',
      'default' => '0.00',
         'sort' => true,
         'help' => '$'
);
if ($opts['cgi']['persist']['oper'] == 'Vente') {
    $opts['fdd']['pr_prixunite']['name'] = 'Prix de vente';
} else {
    $opts['fdd']['pr_prixunite']['name'] = "Prix à l'achat";
}
$opts['fdd']['status_code'] = array(
         'name' => 'Status code',
       'select' => 'T',
      'options' => 'VDR',
       'maxlen' => '1',
      'default' => 'C',
       'values' => array('table'  => 'pme_statuscodes',
                         'column' => 'code',
                         'description' => array('columns' => array('code', 'status_name'),
                                                'divs'    => array (' - '))
                        )
);
if ($opts['cgi']['persist']['oper'] == 'Vente') {
    $opts['fdd']['pr_ingredients'] = array(
         'name' => '# ingredients',
       'select' => 'T',
      'options' => 'VL',
          'css' => array('postfix' => 'detailsbutton'),
      'URLdisp' => 'Ingredient(s): $value',
          'URL' => 'prodcomposition.php?pr_code=$key'
    );
}

echo '
<script>
    PME_js_setPageTitle("' . $title . '", "' . $titleLink . '");
</script>
';

// Now important call to phpMyEdit

new phpMyEdit_MultiQuery($opts);

//eof

