<menu class='pme-menu'>
    <li><a href='../index.php'><img class="pme-navigation" src="../images/pme-home.png" alt="Home"></a></li>
    <li><a href='pme_changelog.php'>ChangeLog</a></li>
    <li><a href='pme_symbols.php'>Symbols</a></li>
    <li><a href='pme_languages.php'>Languages</a></li>
    <li><a href='pme_statuscodes.php'>StatusCodes</a></li>
    <li><a href='pme_users.php'>Users</a></li>
    <li class='not-horizontal' disabled='disabled'>---</li>
    <li class='not-vertical'><a href='getstarted-index.php'>Examples</a></li>
    <li class='not-horizontal'><a href='countries.php'>Countries</a></li>
    <li class='not-horizontal'><a href='taxrates.php'>TaxRates</a></li>
</menu>